import { fetchWithTimeout } from "@/lib/fetch-timeout";

export const workerProxies = [
  "https://berkas.test075-123.workers.dev/",
  "https://berkas.test078-123.workers.dev/",
  "https://berkas.test077-123.workers.dev/",
  "https://berkas.test076-123.workers.dev/",
  "https://berkas.test068-abc.workers.dev/",
  "https://berkas.test073-123.workers.dev/",
  "https://berkas.test074-123.workers.dev/",
  "https://berkas.test072-123.workers.dev/",
  "https://berkas.test071-123.workers.dev/",
  "https://berkas.test070-123.workers.dev/",
  "https://berkas.test069-123.workers.dev/",
  "https://berkas.test063-123.workers.dev/",
  "https://berkas.test064-123.workers.dev/",
  "https://berkas.test065-123.workers.dev/",
  "https://berkas.test061-123.workers.dev/",
  "https://berkas.test059-123.workers.dev/",
  "https://berkas.test060-123.workers.dev/",
  "https://berkas.test062-123.workers.dev/",
  "https://berkas.test055-123.workers.dev/",
  "https://berkas.test058-123.workers.dev/",
  "https://berkas.test057-123.workers.dev/",
  "https://berkas.test056-123.workers.dev/",
  "https://berkas.test052-123.workers.dev/",
  "https://berkas.test054-123.workers.dev/",
  "https://berkas.test053-123.workers.dev/",
  "https://berkas.test051-123.workers.dev/",
  "https://berkas.test047-123.workers.dev/",
  "https://berkas.test049-123.workers.dev/",
  "https://berkas.test050-123.workers.dev/",
  "https://berkas.test048-123.workers.dev/",
  "https://berkas.test045.workers.dev/",
  "https://berkas.test046-43r.workers.dev/",
  "https://berkas.test98-a64.workers.dev/",
  "https://berkas.test97-f4b.workers.dev/",
  "https://berkas.test96-27b.workers.dev/",
  "https://berkas.test95-7d8.workers.dev/",
  "https://berkas.test100-1ff.workers.dev/",
  "https://berkas.test-zxcstream.workers.dev/",
  "https://berkas.test038.workers.dev/",
  "https://berkas.test032.workers.dev/",
  "https://berkas.test034.workers.dev/",
  "https://berkas.test035.workers.dev/",
  "https://berkas.test033.workers.dev/",
  "https://berkas.test031.workers.dev/",
  "https://berkas.test027.workers.dev/",
  "https://berkas.test025.workers.dev/",
  "https://berkas.test026.workers.dev/",
  "https://berkas.test024.workers.dev/",
  "https://berkas.test023.workers.dev/",
  "https://berkas.test022.workers.dev/",
  "https://berkas.test021.workers.dev/",
  "https://berkas.test017.workers.dev/",
  "https://berkas.test019.workers.dev/",
  "https://berkas.test018.workers.dev/",
  "https://berkas.test020.workers.dev/",
  "https://berkas.test013.workers.dev/",
  "https://berkas.test015-505.workers.dev/",
  "https://berkas.test014-25a.workers.dev/",
  "https://berkas.test09-635.workers.dev/",
  "https://berkas.test010-f3d.workers.dev/",
  "https://berkas.test011.workers.dev/",
  "https://berkas.test012.workers.dev/",
  "https://berkas.test05-187.workers.dev/",
  "https://berkas.test07-84f.workers.dev/",
  "https://berkas.test08-0df.workers.dev/",
  "https://berkas.test01-05a.workers.dev/",
  "https://berkas.test02-663.workers.dev/",
  "https://berkas.test03-4fb.workers.dev/",
  "https://rapid-rain-5111.berkas002.workers.dev/",
  "https://noisy-star-55c7.berkas003.workers.dev/",
  "https://wispy-frog-30dc.berkas007.workers.dev/",
  "https://still-sound-93be.berkas009.workers.dev/",
  "https://bitter-cake-30a3.berkas0001.workers.dev/",
  "https://floral-queen-8843.berkas0004.workers.dev/",
  "https://late-band-520f.berkas0003.workers.dev/",
  "https://wispy-credit-3692.berkas0005.workers.dev/",
  "https://proud-paper-2687.berkas0007.workers.dev/",
  "https://muddy-butterfly-b8c9.invalid2.workers.dev/",
  "https://holy-tooth-f9cb.invalid3.workers.dev/",
  "https://nameless-wildflower-767a.invalid6.workers.dev/",
  "https://empty-frog-2095.invalid7.workers.dev/",
  "https://black-cake-f379.invalid9.workers.dev/",
  "https://long-haze-0a62.garlic2.workers.dev/",
  "https://rough-meadow-63f9.cabbage3.workers.dev/",
  "https://aged-dawn-0319.whattheheal2.workers.dev/",
  "https://broken-meadow-04ae.whattheheal3.workers.dev/",
  "https://floral-math-77db.cabbage8.workers.dev/",
  "https://misty-surf-ee67.cabbage10.workers.dev/",
  "https://purple-dust-6060.cabbage12.workers.dev/",
  "https://winter-sky-d6cf.eggplant5.workers.dev/",
  //
  "https://zxcstream.berkas44.workers.dev/",
  "https://zxcstream.berkas43.workers.dev/",
  "https://zxcstream.berkas42.workers.dev/",
  "https://zxcstream.berkas41.workers.dev/",
  "https://zxcstream.berkas40.workers.dev/",
  "https://zxcstream.berkas39.workers.dev/",
  "https://zxcstream.berkas38.workers.dev/",
  "https://zxcstream.berkas37.workers.dev/",
  "https://zxcstream.berkas36.workers.dev/",
  "https://zxcstream.berkas35.workers.dev/",
  "https://zxcstream.berkas34.workers.dev/",
  "https://zxcstream.berkas33.workers.dev/",
  "https://zxcstream.berkas32.workers.dev/",
  "https://zxcstream.berkas31.workers.dev/",
  "https://zxcstream.berkas30.workers.dev/",
  "https://zxcstream.berkas29.workers.dev/",
  "https://zxcstream.berkas28.workers.dev/",
  "https://zxcstream.berkas27.workers.dev/",
  "https://berkas.berkas26.workers.dev/",
  "https://berkas.berkas25.workers.dev/",
  "https://zxcstream.berkas24.workers.dev/",
  "https://zxcstream.berkas23.workers.dev/",
  "https://zxcstream.berkas22.workers.dev/",
  "https://zxcstream.berkas21.workers.dev/",
  "https://zxcstream.berkas20.workers.dev/",
  "https://zxcstream.berkas19.workers.dev/",
  "https://zxcstream.berkas18.workers.dev/",
  "https://zxcstream.berkas17.workers.dev/",
  "https://zxcstream.berkas16.workers.dev/",
  "https://zxcstream.berkas15.workers.dev/",
  "https://zxcstream.berkas14.workers.dev/",
  "https://zxcstream.berkas13.workers.dev/",
  "https://zxcstream.berkas12.workers.dev/",
  "https://zxcstream.berkas11.workers.dev/",
  "https://zxcstream.berkas10.workers.dev/",
  "https://zxcstream.berkas9.workers.dev/",
  "https://zxcstream.berkas8.workers.dev/",
  "https://zxcstream.berkas7.workers.dev/",
  "https://zxcstream.berkas6.workers.dev/",
  "https://zxcstream.berkas5.workers.dev/",
  "https://zxcstream.berkas4.workers.dev/",
  "https://zxcstream.berkas3.workers.dev/",
  "https://zxcstream.berkas2.workers.dev/",
  "https://zxcstream.berkas1.workers.dev/",
  //
  "https://tight-glitter-3cac.berkas04.workers.dev/",
  "https://tiny-meadow-5f2b.berkas03.workers.dev/",
  "https://rapid-forest-0c46.berkas02.workers.dev/",
  "https://autumn-bonus-a535.berkas01.workers.dev/",
  "https://zxcstream.berkas65.workers.dev/",
  "https://zxcstream.berkas64.workers.dev/",
  "https://zxcstream.berkas63.workers.dev/",
  "https://zxcstream.berkas61.workers.dev/",
  "https://zxcstream.berkas60.workers.dev/",
  "https://zxcstream.berkas58.workers.dev/",
  "https://zxcstream.berkas57.workers.dev/",
  "https://zxcstream.berkas55.workers.dev/",
  "https://zxcstream.berkas54.workers.dev/",
  "https://zxcstream.berkas53.workers.dev/",
  "https://zxcstream.berkas52.workers.dev/",
  "https://zxcstream.berkas51.workers.dev/",
  "https://zxcstream.berkas50.workers.dev/",
  "https://zxcstream.berkas49.workers.dev/",
  "https://zxcstream.berkas48.workers.dev/",
  "https://zxcstream.berkas47.workers.dev/",
  "https://zxcstream.berkas46.workers.dev/",
  "https://zxcstream.berkas45.workers.dev/",
  //
  "https://snowy-brook-8333.berkas016.workers.dev/",
  "https://withered-wind-d29d.berkas015.workers.dev/",
  "https://dry-sea-54e2.berkas014.workers.dev/",
  "https://late-lake-bf67.berkas013.workers.dev/",
  "https://tight-fog-8f33.berkas012.workers.dev/",
  "https://dawn-sound-29da.berkas011.workers.dev/",
  "https://hidden-term-bd90.berkas010.workers.dev/",
  "https://long-pine-34a6.berkas09.workers.dev/",
  "https://lingering-frog-21bf.berkas08.workers.dev/",
  "https://royal-boat-ed13.berkas07.workers.dev/",
  "https://bitter-disk-bffb.berkas06.workers.dev/",
  "https://rough-waterfall-90f0.berkas05.workers.dev/",
  //
  "https://late-meadow-f5cf.icarus042.workers.dev/",
  "https://icy-frost-2f13.icarus053.workers.dev/",
  "https://yellow-truth-b7cf.icarus057.workers.dev/",
  "https://fragrant-wind-40f0.icarus059.workers.dev/",
  "https://long-meadow-047f.vps9-9ce.workers.dev/",
  "https://damp-rain-dad6.icarus048.workers.dev/",
  "https://old-smoke-c852.icarus043.workers.dev/",
  "https://autumn-sky-7829.icarus041.workers.dev/",
  "https://super-tree-8f2e.icarus040.workers.dev/",
  "https://steep-sky-b7c6.icarus039.icarus039.workers.dev/",
  "https://patient-base-d281.icarus038.workers.dev/",
  "https://small-bonus-631a.icarus044.workers.dev/",
  "https://tight-fog-810b.icarus046.workers.dev/",
  "https://sweet-frost-4413.icarus037.workers.dev/",
  "https://wild-frost-90b0.icarus035.workers.dev/",
  "https://frosty-term-80f0.icarus036.workers.dev/",
  "https://misty-wildflower-f895.icarus034.workers.dev/",
  //
  "https://shy-rice-3f7d.gmail1.workers.dev/",
  "https://tiny-night-3f17.gmail3.workers.dev/",
  "https://damp-resonance-edc1.facebook1.workers.dev/",
  "https://round-term-b231.facebook2-891.workers.dev/",
  "https://dry-morning-c50d.facebook3.workers.dev/",
  "https://flat-resonance-2702.facebook4.workers.dev/",
  "https://aged-thunder-925d.facebook5.workers.dev/",

  "https://throbbing-thunder-2359.facebook6.workers.dev/",
  "https://quiet-heart-aaca.facebook7.workers.dev/",
  "https://fancy-math-b578.facebook8.workers.dev/",
  "https://square-fog-9d75.facebook9.workers.dev/",

  "https://steep-fog-c825.facebook10.workers.dev/",
  "https://crimson-sky-185f.facebook11.workers.dev/",
  "https://winter-wind-3b69.facebook12.workers.dev/",
  "https://hidden-breeze-2e88.facebook13.workers.dev/",

  "https://holy-snowflake-2fb4.orion0001.workers.dev/",
  "https://hidden-moon-0989.orion0002.workers.dev/",
  "https://throbbing-pine-dceb.orion0003.workers.dev/",
  "https://gentle-boat-15ec.orion0004.workers.dev/",
  "https://lingering-glade-54f6.orion0005.workers.dev/",
  "https://lively-bush-0572.orion0006.workers.dev/",
  "https://broken-pond-08af.orion007.workers.dev/",
  "https://wispy-sea-c35e.orion008.workers.dev/",
  "https://morning-paper-2c32.orion009.workers.dev/",
  "https://dry-rain-6c61.orion0010.workers.dev/",

  "https://late-firefly-ca73.orion0011.workers.dev/",
  "https://sparkling-bush-c28f.orion0012.workers.dev/",
  "https://billowing-glitter-4e38.orion0013.workers.dev/",
  "https://snowy-grass-18ac.orion0014.workers.dev/",

  "https://billowing-hat-4025.orion0015.workers.dev/",
  "https://curly-glitter-b0c4.orion0016.workers.dev/",
  "https://restless-hill-ae23.orion0017.workers.dev/",
  "https://dark-wave-57fc.orion0018.workers.dev/",

  "https://morning-voice-8620.orion0019.workers.dev/",
  "https://cold-hat-5c06.orion0020.workers.dev/",
  "https://green-resonance-ba27.orion001.workers.dev/",
  "https://plain-tooth-a5ef.orion002.workers.dev/",

  "https://morning-mountain-b270.orion003.workers.dev/",
  "https://lively-rice-79f8.orion004.workers.dev/",
  "https://young-poetry-2f1e.orion005.workers.dev/",
  "https://broken-fire-37fb.orion006.workers.dev/",

  "https://plain-waterfall-fe4e.facebook14.workers.dev/",
  "https://tight-king-45e5.facebook15.workers.dev/",

  "https://throbbing-dream-bb83.test62-63e.workers.dev/",
  "https://small-hall-439b.test83-291.workers.dev/",
  "https://rough-bonus-f4e3.test82-ac2.workers.dev/",
  "https://quiet-sun-4390.test80-1f4.workers.dev/",

  "https://curly-sea-0553.test79-29a.workers.dev/",
  "https://mute-bonus-b2b6.test78-564.workers.dev/",
  "https://fragrant-silence-a7d1.test77-a68.workers.dev/",
  "https://weathered-king-9f51.test76-4e9.workers.dev/",

  "https://delicate-dream-a0ac.test75-da4.workers.dev/",
  "https://twilight-mode-af23.test74-635.workers.dev/",
  "https://sweet-feather-58ef.test73-bfb.workers.dev/",
  "https://restless-term-9ca1.test72-165.workers.dev/",
  "https://wispy-sea-969e.test71-dc9.workers.dev/",
  "https://silent-rain-377c.test68-6e8.workers.dev/",
  "https://flat-darkness-ef7a.test70-ee3.workers.dev/",
  "https://restless-brook-d944.test67-989.workers.dev/",
  "https://long-dew-a85b.test84-c55.workers.dev/",
  "https://muddy-sky-afea.test92-0aa.workers.dev/",

  "https://jolly-bread-cd55.orion0007.workers.dev/",
  "https://nameless-paper-1bf8.orion0008.workers.dev/",
  "https://super-hat-bcbd.orion0009.workers.dev/",
  "https://old-fog-35b0.orion00010.workers.dev/",

  ///////////////////////////////////////////////////
  "https://dry-moon-e266.test66-8cc.workers.dev/",
  "https://fragrant-rice-8998.test65-8de.workers.dev/",
  "https://restless-resonance-a8a8.test63-bfc.workers.dev/",
  "https://nameless-tooth-8cbb.test64-0d5.workers.dev/",

  "https://spring-darkness-8beb.test61-86c.workers.dev/",
  "https://odd-river-ed9f.test29-be6.workers.dev/",
  "https://soft-shadow-1443.expired8.workers.dev/",
  "https://floral-limit-aeb0.expired9.workers.dev/",
  "https://still-mode-5f32.expired6.workers.dev/",
  "https://cool-wave-a9c1.expired7.workers.dev/",
  "https://shrill-smoke-e6eb.test60-598.workers.dev/",
  "https://twilight-resonance-eb4d.test28-f24.workers.dev/",

  // "https://billowing-rain-7239.test27-15e.workers.dev/",
];

export function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];

  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }

  return a;
}

export async function workerProxyHealth(proxies: string[]) {
  const shuffledProxies = shuffle(proxies);

  for (const proxy of shuffledProxies) {
    try {
      const res = await fetchWithTimeout(
        proxy,
        { method: "HEAD", headers: { Range: "bytes=0-1" } },
        7000,
      );

      if (res.ok) return proxy;
    } catch (err: any) {
      console.error(
        `[PROXY] ${proxy} → ${err?.name || err?.message || "failed"}`,
      );
    }
  }

  return null;
}
